### ISSUE TITLE
Step 1: install npx

### ISSUE THREAD

**Issue by molinto** [create-node/create-node-app#11]
Step 1: install npx

Seems to be missing from your docs. I can from TechCrunch -> KubeSail, signed up via Github.
Mentions 'npx create-node-app my-app' first, but I don't have/know what npx is.

**Fix: npm install -g npx**

**Comment by piecioshka** [comment]
@molinto you should have npm 5.6+

**Comment by pastudan** [comment]
Hey @molinto, @piecioshka is correct, npx comes pre-installed with recent versions of npm, so I did not include these in the instructions. Thanks for trying out create node app!
